name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: any

dependencies:
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.4
  shelf_router: ^1.1.3
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  mongo_dart: ^0.9.1
  shelf_web_socket: ^1.0.4
